// AUTO-GENERATED by scripts/generate-home-map.mjs — do not edit by hand.
// Projection constants for public/maps/home-map-atlas.{webp,jpg}: overlay
// components use these to place labels/pins on the image in percent terms.
export const HOME_MAP = {
  width: 1280, height: 520, scale: 2,
  zoom: 3.060373, centerX: 0.79159865, centerY: 0.58214346,
}

const worldSize = 512 * Math.pow(2, HOME_MAP.zoom)

// → { leftPct, topPct } position on the rendered image for CSS placement.
export function projectToImagePct(lng, lat) {
  const mx = (lng + 180) / 360
  const s = Math.sin((lat * Math.PI) / 180)
  const my = 0.5 - Math.log((1 + s) / (1 - s)) / (4 * Math.PI)
  const x = (mx - HOME_MAP.centerX) * worldSize + HOME_MAP.width / 2
  const y = (my - HOME_MAP.centerY) * worldSize + HOME_MAP.height / 2
  return { leftPct: (x / HOME_MAP.width) * 100, topPct: (y / HOME_MAP.height) * 100 }
}
